/**
 * build-css.js
 * ------------------------------------------------------------------
 * Extracts the inline <style> block from every EJS view, scopes each
 * page's rules under `body.page-<name>` (so styles from one page can
 * never bleed into another), and concatenates everything into a single
 * stylesheet: public/stylesheet/style.css
 *
 * A hand-written GLOBAL layer (design tokens + the shared navbar) is
 * prepended so the shared header looks consistent on every page.
 *
 * Run:  node scripts/build-css.js
 */
const fs = require("fs");
const path = require("path");
const postcss = require("postcss");
const prefixer = require("postcss-prefix-selector");

const VIEWS = path.join(__dirname, "..", "views");
const OUT = path.join(__dirname, "..", "public", "stylesheet", "style.css");

// ── GLOBAL LAYER ──────────────────────────────────────────────────
// Shared design tokens (union of what every page used) + the one
// navbar definition. Navbar selectors are ID-scoped (#navbar ...) so
// they style the shared header consistently across all pages.
const GLOBAL = `/* =================================================================
   GLOBAL LAYER — shared tokens + shared navbar
   (auto-generated by scripts/build-css.js — do not edit by hand;
    page-specific CSS lives in the scoped sections below)
   ================================================================= */
:root {
  --bg:#03040a; --neon:#00f5c4; --neon2:#7b61ff; --neon3:#ff6b6b;
  --text:#f0f0f0; --muted:rgba(240,240,240,0.5);
  --surface:rgba(255,255,255,0.03); --surface2:rgba(255,255,255,0.055);
  --border:rgba(255,255,255,0.07); --border-h:rgba(0,245,196,0.22);
  --up:#00e676; --dn:#ff6b6b; --amber:#ffb800;
}

* { box-sizing:border-box; }

/* ── Shared navbar (used by views/partials/header.ejs) ─────────── */
#navbar {
  position:fixed; top:0; left:0; right:0; z-index:1000;
  display:flex; justify-content:space-between; align-items:center;
  padding:0 2%;
  backdrop-filter:blur(20px);
  background:rgba(0,0,0,0.5);
  border-bottom:1px solid var(--border);
  height:60px;
  animation:navIn .6s ease both;
  font-family:'DM Sans',sans-serif;
}
@keyframes navIn { from{opacity:0;transform:translateY(-20px)} to{opacity:1;transform:translateY(0)} }

#navbar .nav-left { display:flex; align-items:center; gap:0; }
#navbar .nav-brand {
  display:flex; align-items:center; gap:10px;
  padding:0 20px; border-right:1px solid var(--border);
  height:60px; text-decoration:none;
}
#navbar .nav-brand-icon {
  width:32px; height:32px; border-radius:8px;
  background:linear-gradient(135deg,var(--neon),var(--neon2));
  display:flex; align-items:center; justify-content:center;
  font-family:'Syne'; font-size:0.8rem; font-weight:800; color:#03040a;
}
#navbar .nav-brand-text { font-family:'Syne'; font-size:1rem; font-weight:800; color:var(--text); }

#navbar .nav-tabs { display:flex; align-items:center; height:60px; }
#navbar .nav-tab {
  display:flex; align-items:center; height:100%;
  padding:0 28px; text-decoration:none;
  font-size:0.9rem; color:var(--muted);
  border-bottom:2px solid transparent;
  transition:color .25s, border-color .25s; white-space:nowrap;
}
#navbar .nav-tab:hover { color:var(--text); }
#navbar .nav-tab.active { color:var(--neon); border-bottom-color:var(--neon); }

#navbar .nav-right { display:flex; align-items:center; gap:10px; }
#navbar .nav-pill {
  display:flex; align-items:center; gap:7px;
  background:rgba(255,255,255,0.05); border:1px solid var(--border);
  border-radius:8px; padding:7px 14px; font-size:0.82rem; color:var(--muted);
  cursor:pointer; transition:all .25s;
}
#navbar .nav-pill:hover { border-color:var(--neon); color:var(--neon); }
#navbar .nav-pill.active { background:rgba(0,245,196,0.08); border-color:rgba(0,245,196,0.35); color:var(--neon); }
#navbar .nav-pill svg { width:14px; height:14px; }
#navbar .nav-divider { width:1px; height:28px; background:var(--border); }
#navbar .nav-currency {
  display:flex; align-items:center; gap:6px;
  background:rgba(255,255,255,0.05); border:1px solid var(--border);
  border-radius:8px; padding:7px 14px; font-size:0.82rem; color:var(--text);
  cursor:pointer; transition:all .25s;
}
#navbar .nav-currency:hover { border-color:var(--neon2); }
#navbar .nav-currency select {
  background:transparent; border:none; color:var(--text);
  font-family:'DM Sans'; font-size:0.82rem; outline:none; cursor:pointer;
}
#navbar .nav-currency select option { background:#0d0f1a; }
#navbar .nav-settings {
  width:36px; height:36px; border-radius:8px;
  background:rgba(255,255,255,0.05); border:1px solid var(--border);
  display:flex; align-items:center; justify-content:center;
  cursor:pointer; transition:all .25s; color:var(--muted);
}
#navbar .nav-settings:hover { border-color:var(--neon); color:var(--neon); }
#navbar .tb-user {
  display:flex; align-items:center; gap:10px;
  padding:6px 14px 6px 8px;
  background:rgba(255,255,255,0.05); border:1px solid var(--border);
  border-radius:8px; cursor:pointer; transition:all .25s; text-decoration:none;
}
#navbar .tb-user:hover { border-color:var(--neon); }
#navbar .tb-avatar {
  width:28px; height:28px; border-radius:50%;
  background:linear-gradient(135deg,var(--neon),var(--neon2));
  display:flex; align-items:center; justify-content:center;
  font-size:.72rem; font-weight:800; color:#03040a; flex-shrink:0;
}
#navbar .tb-name { font-size:0.82rem; color:var(--text); }
#navbar .nav-auth-link {
  padding:8px 18px; border-radius:8px; border:1px solid rgba(255,255,255,0.2);
  color:var(--text); font-size:0.85rem; text-decoration:none; transition:all .25s;
}
#navbar .nav-auth-link:hover { border-color:var(--neon); color:var(--neon); }
#navbar .nav-auth-link.primary {
  background:linear-gradient(135deg,var(--neon),var(--neon2));
  color:#000; font-weight:700; border:none;
}
#navbar .nav-logout {
  width:36px; height:36px; border-radius:8px;
  background:rgba(255,107,107,0.08); border:1px solid rgba(255,107,107,0.2);
  display:flex; align-items:center; justify-content:center;
  cursor:pointer; transition:all .25s; color:var(--neon3); text-decoration:none;
}
#navbar .nav-logout:hover { background:rgba(255,107,107,0.15); border-color:var(--neon3); }

/* Pages that previously had no navbar need room for the fixed header */
body.page-login, body.page-signup, body.page-dashboard { padding-top:60px; }

/* =================================================================
   PAGE-SCOPED SECTIONS (extracted from each view, auto-scoped)
   ================================================================= */
`;

// Map each EJS file to its body page-class suffix
const PAGES = {
  "index.ejs": "index",
  "login.ejs": "login",
  "signup.ejs": "signup",
  "dashboard.ejs": "dashboard",
  "categories.ejs": "categories",
  "Portfolio.ejs": "portfolio",
  "news.ejs": "news",
  "stockinfo.ejs": "stockinfo",
  "virtual-trading.ejs": "virtual-trading",
};

function extractStyle(html) {
  const m = html.match(/<style[^>]*>([\s\S]*?)<\/style>/i);
  return m ? m[1] : "";
}

async function scope(css, page) {
  const prefix = `body.page-${page}`;
  const result = await postcss([
    prefixer({
      prefix,
      transform(prefixSel, selector, prefixedSelector, filePath, rule) {
        // Leave @keyframes step selectors (from/to/0%) untouched
        const parent = rule && rule.parent;
        if (parent && parent.type === "atrule" && /keyframes/i.test(parent.name)) {
          return selector;
        }
        // Map root/html/body onto the page wrapper itself
        const s = selector.trim();
        if (s === ":root" || s === "html" || s === "body" || s === "html body") {
          return prefixSel;
        }
        if (s === "*") return `${prefixSel} *`;
        return prefixedSelector;
      },
    }),
  ]).process(css, { from: undefined });
  return result.css;
}

(async () => {
  let out = GLOBAL;
  for (const [file, page] of Object.entries(PAGES)) {
    const fp = path.join(VIEWS, file);
    const html = fs.readFileSync(fp, "utf8");
    const css = extractStyle(html);
    if (!css.trim()) {
      console.warn(`! no <style> found in ${file}`);
      continue;
    }
    const scoped = await scope(css, page);
    out += `\n/* ===== ${file}  →  body.page-${page} ===== */\n${scoped}\n`;
    console.log(`✓ scoped ${file} (${css.length} chars)`);
  }
  fs.mkdirSync(path.dirname(OUT), { recursive: true });
  fs.writeFileSync(OUT, out, "utf8");
  console.log(`\n✅ wrote ${OUT} (${out.length} chars)`);
})();
